version: 2.1

orbs:
  phpcs: vip_migration/phpcs@0.0.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - phpcs/install-phpcs:
          working-dir: /vendor/bin/phpcs

workflows:
  example-workflow:
    jobs:
      - example-job