version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout

      - run: sudo apt install wget
      - run: wget http://pear.php.net/go-pear.phar
      - run: php go-pear.phar
      - run: pear install PHP_CodeSniffer
      - run: php -v
      - run:
          name: "Drupal Sniffer"
          command: |
            phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,yml web/modules/custom/ web/themes/custom

workflows:
  1st-Workflow:
    jobs:
      - build
